Repository chamilo/chamilo-lms, pull requests merged in 2020-11, with the labels that each got.

#3512 Course: Fix default sort order in the tracking menu - refs GH#3510
  main/inc/lib/SortableTableFromArray.php
  main/inc/lib/sortable_table.class.php
Labels: Enhancement

#3550 Añadiendo archivos de ejemplo para api de chamilo BT#17801
  main/webservices/api/example/add_courses_session.php
  main/webservices/api/example/add_users_session.php
  main/webservices/api/example/authenticate.php
  main/webservices/api/example/course_agenda.php
  main/webservices/api/example/course_announcement.php
  main/webservices/api/example/course_announcements.php
  main/webservices/api/example/course_descriptions.php
  main/webservices/api/example/course_documents.php
  main/webservices/api/example/course_forum.php
  main/webservices/api/example/course_forumcategories.php
  main/webservices/api/example/course_forumthread.php
  main/webservices/api/example/course_info.php
  main/webservices/api/example/course_learnpath.php
  main/webservices/api/example/save_session.php
  main/webservices/api/example/save_user.php
  main/webservices/api/example/update_user_from_username.php
  main/webservices/api/example/user_courses.php
  main/webservices/api/example/user_message_read.php
  main/webservices/api/example/user_message_unread.php
  main/webservices/api/example/user_messages.php
  main/webservices/api/example/user_profile.php
  main/webservices/api/example/user_sessions.php
  main/webservices/api/example/username_exist.php
Labels: Documentation, Enhancement

#3559 Nueva forma de pago para comprar cursos
  plugin/buycourses/database.php
  plugin/buycourses/lang/english.php
  plugin/buycourses/lang/spanish.php
  plugin/buycourses/src/buy_course_plugin.class.php
  plugin/buycourses/src/paymentsetup.php
  plugin/buycourses/src/process.php
  plugin/buycourses/src/process_confirm.php
  plugin/buycourses/src/tpv_error.php
  plugin/buycourses/src/tpv_response.php
  plugin/buycourses/src/tpv_success.php
  plugin/buycourses/view/paymentsetup.tpl
Labels: Feature request, On hold - Can't integrate
