Repository chamilo/chamilo-lms, pull requests merged in 2021-08, with the labels that each got.

#3931 Send security token for chat and social wall
  main/inc/lib/chat.lib.php
  main/inc/lib/javascript/chat/js/chat.js
  main/inc/lib/security.lib.php
  main/inc/lib/social.lib.php
  main/social/home.php
  main/social/profile.php
Labels: Requires testing/validation

#3937 remove line-break filtering on save after editing
  main/document/edit_document.php
Labels: Enhancement

#3939 Search: Add search diagnosis from preprodparkur BT#18899
  assets/vue/components/layout/DashboardLayout.vue
  assets/vue/store/security.js
  public/main/inc/ajax/extra_field.ajax.php
  public/main/inc/ajax/model.ajax.php
  public/main/inc/lib/api.lib.php
  public/main/inc/lib/extra_field.lib.php
  public/main/inc/lib/extra_field_value.lib.php
  public/main/inc/lib/pear/HTML/QuickForm/element.php
  public/main/inc/lib/sessionmanager.lib.php
  public/main/search/bootstrap/bootstrap.min.css
  public/main/search/bootstrap/bootstrap.min.js
  public/main/search/cropper/cropper.min.css
  public/main/search/cropper/cropper.min.js
  public/main/search/load_search.php
  public/main/search/search.php
  public/main/search/select2/select2.min.css
  public/main/search/select2/select2.min.js
  public/main/template/default/search/search_extra_field.html.twig
  src/CoreBundle/Entity/ExtraFieldSavedSearch.php
  src/CoreBundle/Settings/SessionSettingsSchema.php
Labels: Feature request
